#!/usr/bin/env bash
set -euo pipefail
if [[ -z "${PACK_DIR:-}" ]]; then
  PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
# shellcheck disable=SC1090
source "$PACK_DIR/configs/path_policy.env"
export PACK_DIR WORKSPACE_DIR NANOCHAT_DIR NANOCHAT_BASE_DIR LOCAL_TEXT_DIR DOWNLOAD_DIR REPORT_DIR DIST_DIR
export TMPDIR XDG_CACHE_HOME XDG_CONFIG_HOME HF_HOME TORCH_HOME PIP_CACHE_DIR UV_CACHE_DIR
export WANDB_DIR CARGO_HOME RUSTUP_HOME NANOCHAT_DTYPE WANDB_MODE WANDB_DISABLED WANDB_SILENT PYTHONNOUSERSITE
mkdir -p "$WORKSPACE_DIR" "$NANOCHAT_BASE_DIR" "$LOCAL_TEXT_DIR" "$DOWNLOAD_DIR" "$REPORT_DIR" "$DIST_DIR" \
  "$TMPDIR" "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$HF_HOME" "$TORCH_HOME" "$PIP_CACHE_DIR" "$UV_CACHE_DIR" \
  "$WANDB_DIR" "$CARGO_HOME" "$RUSTUP_HOME"
