#!/usr/bin/env python3
"""Create scripts/chat_sft_be.py for Belarusian-only nanochat SFT.

The patch is non-destructive: it never modifies scripts/chat_sft.py. It copies
upstream chat_sft.py and replaces the default English-heavy mixture with two
CustomJSON files under NANOCHAT_BASE_DIR:
  - identity_conversations.jsonl
  - identity_conversations_val.jsonl
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MARKER = "Belarusian-only CustomJSON"
GENERIC_EVALS_MARKER = "BELKA_DISABLE_GENERIC_EVALS"
GENERIC_EVALS_GATE = '''    # BELKA_DISABLE_GENERIC_EVALS skips English generic evals for Belarusian-only SFT
    _skip_generic = os.environ.get("BELKA_DISABLE_GENERIC_EVALS", "") == "YES"
    if not _skip_generic and args.chatcore_every > 0 and (last_step or (step > 0 and step % args.chatcore_every == 0)):'''

REPLACEMENT = '''# SFT data mixture and DataLoader
identity_conversations_filepath = os.path.join(base_dir, "identity_conversations.jsonl")
identity_conversations_val_filepath = os.path.join(base_dir, "identity_conversations_val.jsonl")
train_tasks = [
    CustomJSON(filepath=identity_conversations_filepath),
    CustomJSON(filepath=identity_conversations_filepath),
]
train_dataset = TaskMixture(train_tasks)
print0(f"Training mixture: {len(train_dataset):,} rows (Belarusian-only CustomJSON x2)")
val_dataset = TaskMixture([
    CustomJSON(filepath=identity_conversations_val_filepath),
])
'''


def ensure_imports(text: str) -> str:
    if "from tasks.customjson import CustomJSON" not in text:
        # Insert near other task imports; safe if upstream layout changes.
        m = re.search(r"(^from tasks\.[^\n]+\n)(?!from tasks\.)", text, flags=re.M)
        if m:
            text = text[:m.end()] + "from tasks.customjson import CustomJSON\n" + text[m.end():]
        else:
            text = "from tasks.customjson import CustomJSON\n" + text
    if "from tasks.common import TaskMixture" not in text and "TaskMixture" not in text[:2000]:
        text = "from tasks.common import TaskMixture\n" + text
    return text


def line_start(text: str, pos: int) -> int:
    return text.rfind("\n", 0, pos) + 1


def replace_by_markers(text: str) -> tuple[str, str] | None:
    start = text.find("# SFT data mixture")
    if start < 0:
        return None
    candidates = [
        text.find("# DataLoader is defined here", start),
        text.find("def sft_data_generator", start),
        text.find("train_loader =", start),
    ]
    candidates = [c for c in candidates if c >= 0]
    if not candidates:
        return None
    end = min(candidates)
    end = line_start(text, end)
    if end <= start:
        return None
    return text[:start] + REPLACEMENT + text[end:], "marker-range"


def find_matching_bracket(text: str, open_pos: int) -> int:
    depth = 0
    in_str: str | None = None
    escape = False
    for i in range(open_pos, len(text)):
        ch = text[i]
        if in_str:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == in_str:
                in_str = None
            continue
        if ch in {'"', "'"}:
            in_str = ch
            continue
        if ch in "([{" :
            depth += 1
        elif ch in ")]}":
            depth -= 1
            if depth == 0:
                return i + 1
    return -1


def replace_by_bracket_scan(text: str) -> tuple[str, str] | None:
    start = text.find("train_tasks")
    if start < 0:
        return None
    start = line_start(text, start)
    val_pos = text.find("val_dataset", start)
    if val_pos < 0:
        return None
    open_pos = text.find("(", val_pos)
    if open_pos < 0:
        return None
    end = find_matching_bracket(text, open_pos)
    if end < 0:
        return None
    # Include trailing lines until the next comment or function/data-loader line.
    nl = text.find("\n", end)
    end = len(text) if nl < 0 else nl + 1
    return text[:start] + REPLACEMENT + text[end:], "bracket-scan"


def add_generic_evals_gate(text: str) -> tuple[str, str] | None:
    """Gate the English ChatCORE eval block behind BELKA_DISABLE_GENERIC_EVALS."""
    if GENERIC_EVALS_MARKER in text:
        return text, "already-present"
    cond = "if args.chatcore_every > 0 and (last_step or (step > 0 and step % args.chatcore_every == 0)):"
    if cond in text:
        return text.replace(cond, GENERIC_EVALS_GATE, 1), "chatcore-gate"
    if "chatcore_every" not in text:
        # minimal/synthetic upstream fixture without the ChatCORE block
        return text, "not-applicable"
    return None


def candidate_banner() -> str:
    # Comments, unlike a second docstring, remain valid before a future import.
    return (
        "# Belarusian-only SFT variant generated by "
        "ops/local/patch_nanochat_for_belarusian.py.\n"
        "# Do not edit upstream chat_sft.py for this profile.\n"
    )


def compile_candidate(candidate: str, path: Path) -> str | None:
    try:
        compile(candidate, str(path), "exec", dont_inherit=True)
    except SyntaxError as exc:
        return f"candidate does not compile: {exc.msg} at line {exc.lineno}"
    return None


def create_variant(src: Path, dst: Path, *, overwrite: bool) -> dict:
    if dst.exists() and not overwrite:
        existing = dst.read_text(encoding="utf-8", errors="ignore")
        valid = compile_candidate(existing, dst) is None
        ok = (valid and MARKER in existing and "identity_conversations_val.jsonl" in existing
              and "CustomJSON" in existing and GENERIC_EVALS_MARKER in existing)
        return {"status": "exists", "ok": ok, "path": str(dst),
                "message": "existing chat_sft_be.py kept" if ok else "existing chat_sft_be.py is invalid or incomplete"}
    text = src.read_text(encoding="utf-8")
    text = ensure_imports(text)
    method = None
    result = replace_by_markers(text)
    if result is None:
        result = replace_by_bracket_scan(text)
    if result is None:
        return {"status": "failed", "ok": False, "path": str(dst), "message": "could not locate SFT mixture block"}
    new_text, method = result
    gate = add_generic_evals_gate(new_text)
    if gate is None:
        return {"status": "failed", "ok": False, "path": str(dst), "message": "could not locate ChatCORE eval condition for generic-evals gate"}
    new_text, gate_method = gate
    if MARKER not in new_text or "identity_conversations_val.jsonl" not in new_text:
        return {"status": "failed", "ok": False, "path": str(dst), "message": "verification marker missing after patch"}
    candidate = candidate_banner() + new_text
    compile_error = compile_candidate(candidate, dst)
    if compile_error:
        return {"status": "failed", "ok": False, "path": str(dst), "message": compile_error}
    dst.write_text(candidate, encoding="utf-8")
    return {"status": "written", "ok": True, "path": str(dst), "method": method, "generic_evals_gate": gate_method, "message": "created Belarusian-only SFT script"}


def main() -> None:
    ap = argparse.ArgumentParser(description="Create nanochat scripts/chat_sft_be.py without modifying upstream chat_sft.py")
    ap.add_argument("--nanochat-dir", type=Path, required=True)
    ap.add_argument("--overwrite", action="store_true")
    args = ap.parse_args()
    repo = args.nanochat_dir.expanduser().resolve()
    src = repo / "scripts" / "chat_sft.py"
    dst = repo / "scripts" / "chat_sft_be.py"
    tasks_customjson = repo / "tasks" / "customjson.py"
    if not src.exists():
        raise SystemExit(f"ERROR: missing upstream script: {src}")
    report = {
        "repo": str(repo),
        "source": str(src),
        "destination": str(dst),
        "customjson_file_present": tasks_customjson.exists(),
    }
    report.update(create_variant(src, dst, overwrite=args.overwrite))
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if not report.get("ok"):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
