#!/usr/bin/env python3
"""Build the Belka source-expansion board (metadata only — NO downloads).

Reads:
  - configs/source_expansion_candidates.yaml
  - configs/dataset_sources.yaml
  - reports/DATA_RIGHTS_MANIFEST.json

Writes:
  - reports/public/SOURCE_EXPANSION_BOARD.md
  - reports/public/source_expansion_board.json
  - reports/public/SOURCE_EXPANSION_OWNER_DECISIONS.md

This tool only reads metadata and checks local file availability. It never downloads
data and never modifies corpora.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def _load_yaml(path: Path):
    import yaml  # local import so --help works without PyYAML

    return yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}


def _load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def _available(expected_local_path: str) -> str:
    if not expected_local_path:
        return "unknown"
    p = REPO / expected_local_path
    if p.exists():
        return "available_local"
    # treat a directory prefix match as partial availability
    parent = p.parent
    if parent.exists() and any(parent.iterdir()):
        return "partial_local"
    return "absent"


def _permissioned_ids(rights: dict) -> set[str]:
    cat = rights.get("project_permission_category", {})
    return set(cat.get("permissioned_by_owner", []))


def build_rows(candidates: dict, rights: dict) -> list[dict]:
    permissioned = _permissioned_ids(rights)
    rows = []
    for s in candidates.get("sources", []):
        use = s.get("intended_use", {}) or {}
        redrun = s.get("redistribution", {}) or {}
        sid = s.get("id", "")
        # owner decision needed if not clearly approved/open
        decision = str(s.get("owner_decision", "")).lower()
        needs_decision = not (decision.startswith("approved") or decision.startswith("record_license") or decision.startswith("verify_version"))
        rows.append({
            "id": sid,
            "name": s.get("name", ""),
            "priority": s.get("priority", ""),
            "local_availability": _available(s.get("expected_local_path", "")),
            "license": s.get("original_license", ""),
            "permission_status": s.get("permission_status", ""),
            "permissioned_by_owner": sid in permissioned or "permission" in str(s.get("permission_basis", "")),
            "raw_redistribution": redrun_val(s, "raw_data"),
            "processed_redistribution": redrun_val(s, "processed_data"),
            "training_allowed": bool(use.get("pretraining")) and s.get("priority") in ("A", "B"),
            "eval_allowed": bool(use.get("eval")),
            "risk": ", ".join(s.get("risks", []) or []),
            "owner_decision_needed": needs_decision,
            "owner_decision": s.get("owner_decision", ""),
            "next_step": next_step(s),
        })
    return rows


def redrun_val(s: dict, key: str) -> str:
    return str((s.get("redistribution", {}) or {}).get(key, "unknown"))


def next_step(s: dict) -> str:
    p = s.get("priority")
    avail = s.get("expected_local_path", "")
    if p == "C":
        return "owner license/terms review + approval before any use"
    if s.get("permission_status") == "pending_verification":
        return "record license/terms, then usable for expansion"
    if p == "B":
        return "use under permission overlay; no raw redistribution"
    return f"usable; verify local at {avail}" if avail else "usable"


def render_md(rows: list[dict]) -> str:
    head = (
        "# Belka — Source Expansion Board\n\n"
        "*Generated by `tools/build_source_expansion_board.py` (metadata only; no downloads).*\n\n"
        "Priority: **A** public/open or documented · **B** permissioned-by-owner (no raw redistribution) · "
        "**C** candidate_review_required (blocked until owner approval).\n\n"
        "| id | prio | local | license | permission | raw redist | proc redist | train | eval | risk | decision needed | next step |\n"
        "|---|---|---|---|---|---|---|---|---|---|---|---|\n"
    )
    lines = []
    for r in rows:
        lines.append(
            "| {id} | {priority} | {local_availability} | {license} | {permission_status} | "
            "{raw_redistribution} | {processed_redistribution} | {tr} | {ev} | {risk} | {dn} | {next_step} |".format(
                tr="yes" if r["training_allowed"] else "no",
                ev="yes" if r["eval_allowed"] else "no",
                dn="YES" if r["owner_decision_needed"] else "no",
                **{k: (v if v != "" else "—") for k, v in r.items()},
            )
        )
    return head + "\n".join(lines) + "\n"


def render_owner_decisions(rows: list[dict]) -> str:
    pending = [r for r in rows if r["owner_decision_needed"]]
    out = ["# Belka — Source Expansion: Owner Decisions Needed\n",
           "*Generated by `tools/build_source_expansion_board.py`. These sources are blocked or pending until the owner decides.*\n"]
    if not pending:
        out.append("\nNo sources require an owner decision.\n")
        return "\n".join(out)
    for r in pending:
        out.append(
            f"\n## {r['id']} (priority {r['priority']})\n"
            f"- license: {r['license']}\n"
            f"- permission_status: {r['permission_status']}\n"
            f"- local: {r['local_availability']}\n"
            f"- risk: {r['risk'] or '—'}\n"
            f"- current decision: {r['owner_decision'] or '—'}\n"
            f"- next step: {r['next_step']}\n"
        )
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--candidates", default="configs/source_expansion_candidates.yaml")
    ap.add_argument("--sources", default="configs/dataset_sources.yaml")
    ap.add_argument("--rights", default="reports/DATA_RIGHTS_MANIFEST.json")
    ap.add_argument("--out", default="reports/public", help="output directory")
    ap.add_argument("--dry-run", action="store_true", help="print summary, write nothing")
    args = ap.parse_args()

    candidates = _load_yaml(REPO / args.candidates)
    rights = _load_json(REPO / args.rights)
    rows = build_rows(candidates, rights)

    summary = {
        "total": len(rows),
        "by_priority": {p: sum(1 for r in rows if r["priority"] == p) for p in ("A", "B", "C")},
        "available_local": sum(1 for r in rows if r["local_availability"] == "available_local"),
        "owner_decisions_needed": sum(1 for r in rows if r["owner_decision_needed"]),
    }

    if args.dry_run:
        print("[dry-run] source expansion board summary:")
        print(json.dumps(summary, indent=2))
        return 0

    out = REPO / args.out
    out.mkdir(parents=True, exist_ok=True)
    (out / "source_expansion_board.json").write_text(
        json.dumps({"summary": summary, "sources": rows}, indent=2, ensure_ascii=False), encoding="utf-8")
    (out / "SOURCE_EXPANSION_BOARD.md").write_text(render_md(rows), encoding="utf-8")
    (out / "SOURCE_EXPANSION_OWNER_DECISIONS.md").write_text(render_owner_decisions(rows), encoding="utf-8")
    print(f"wrote board for {summary['total']} sources -> {out}/")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
