#!/usr/bin/env python3
"""Build the Belka source-expansion board (metadata only — NO downloads).

Reads configs/source_expansion_candidates.yaml and writes a source/priority/
availability board. The owner holds full rights to all training data
(licenses retired 2026-08-16), so the board tracks sourcing work
(availability, quality risk, priority), not licensing.

Writes:
  - reports/public/SOURCE_EXPANSION_BOARD.md
  - reports/public/source_expansion_board.json

This tool only reads metadata and checks local file availability. It never
downloads data and never modifies corpora.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def _load_yaml(path: Path):
    import yaml  # local import so --help works without PyYAML

    return yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}


def _available(expected_local_path: str) -> str:
    if not expected_local_path:
        return "unknown"
    p = REPO / expected_local_path
    if p.exists():
        return "available_local"
    parent = p.parent
    if parent.exists() and any(parent.iterdir()):
        return "partial_local"
    return "absent"


def build_rows(candidates: dict) -> list[dict]:
    rows = []
    for s in candidates.get("sources", []):
        use = s.get("intended_use", {}) or {}
        sid = s.get("id", "")
        decision = str(s.get("owner_decision", "")).lower()
        needs_decision = not (decision.startswith("approved") or decision.startswith("verify_version"))
        rows.append({
            "id": sid,
            "name": s.get("name", ""),
            "priority": s.get("priority", ""),
            "local_availability": _available(s.get("expected_local_path", "")),
            "training_planned": bool(use.get("pretraining")) and s.get("priority") in ("A", "B"),
            "eval_planned": bool(use.get("eval")),
            "risk": ", ".join(s.get("risks", []) or []),
            "owner_decision_needed": needs_decision,
            "owner_decision": s.get("owner_decision", ""),
            "next_step": next_step(s),
        })
    return rows


def next_step(s: dict) -> str:
    p = s.get("priority")
    avail = s.get("expected_local_path", "")
    if p == "C":
        return "quality/verification review before any use"
    return f"usable; verify local at {avail}" if avail else "usable"


def render_md(rows: list[dict]) -> str:
    head = (
        "# Belka — Source Expansion Board\n\n"
        "*Generated by `tools/build_source_expansion_board.py` (metadata only; no downloads).*\n\n"
        "Priority: **A** core expansion · **B** literary (capped for diversity) · "
        "**C** backlog (quality review before use).\n\n"
        "| id | prio | local | train | eval | risk | decision needed | next step |\n"
        "|---|---|---|---|---|---|---|---|\n"
    )
    lines = []
    for r in rows:
        lines.append(
            "| {id} | {priority} | {local_availability} | {tr} | {ev} | {risk} | {dn} | {next_step} |".format(
                tr="yes" if r["training_planned"] else "no",
                ev="yes" if r["eval_planned"] else "no",
                dn="YES" if r["owner_decision_needed"] else "no",
                **{k: (v if v != "" else "—") for k, v in r.items()},
            )
        )
    return head + "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--candidates", default="configs/source_expansion_candidates.yaml")
    ap.add_argument("--out", default="reports/public", help="output directory")
    ap.add_argument("--dry-run", action="store_true", help="print summary, write nothing")
    args = ap.parse_args()

    candidates = _load_yaml(REPO / args.candidates)
    rows = build_rows(candidates)

    summary = {
        "total": len(rows),
        "by_priority": {p: sum(1 for r in rows if r["priority"] == p) for p in ("A", "B", "C")},
        "available_local": sum(1 for r in rows if r["local_availability"] == "available_local"),
        "owner_decisions_needed": sum(1 for r in rows if r["owner_decision_needed"]),
    }

    if args.dry_run:
        print("[dry-run] source expansion board summary:")
        print(json.dumps(summary, indent=2))
        return 0

    out = REPO / args.out
    out.mkdir(parents=True, exist_ok=True)
    (out / "source_expansion_board.json").write_text(
        json.dumps({"summary": summary, "sources": rows}, indent=2, ensure_ascii=False), encoding="utf-8")
    (out / "SOURCE_EXPANSION_BOARD.md").write_text(render_md(rows), encoding="utf-8")
    print(f"wrote board for {summary['total']} sources -> {out}/")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
